export const GET_ALL_QUOTES = 'GET_ALL_QUOTES';
export const GET_ALL_QUOTES_SUCCESS = 'GET_ALL_QUOTES_SUCCESS';
export const GET_ALL_QUOTES_ERROR = 'GET_ALL_QUOTES_ERROR';

export const GET_RANDOM_QUOTE = 'GET_RANDOM_QUOTE';
export const GET_RANDOM_QUOTE_SUCCESS = 'GET_RANDOM_QUOTE_SUCCESS';
export const GET_RANDOM_QUOTE_ERROR = 'GET_RANDOM_QUOTE_ERROR';
